### PR TITLE
Sam collector only

### PR DESCRIPTION
**Pull request by sawer297**
stable build, code reviewed and cleaned
pull request #1

### CODE REVIEW

**Comment by sawer297** [comment]
don't merge until after release

**Comment by ndp-opendap** [comment]
- It might be informative to run this through sonar scan.
- I don't think this project has any actual connection to the Hyrax release - check with @jgallagher59701 you can probably merge sooner.
- :shipit:

**Review by ndp-opendap — APPROVED** [review]
- It might be informative to run this through sonar scan.
- I don't think this project has any actual connection to the Hyrax release - check with @jgallagher59701 you can probably merge sooner.
- :shipit:

**Review by jgallagher59701 — APPROVED** [review]
This also can be merged.

**Pull request merged**
